# Generated by Django 5.1.6 on 2025-02-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_register_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
