# Generated by Django 5.1.6 on 2025-02-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_register_users', '0003_alter_user_age_alter_user_id_user_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id_user'], 'verbose_name': 'Usuários'},
        ),
    ]
